export const MAX_KEYWORD_PATTERN_LENGTH = 10_000;
export const MAX_RAW_PATTERN_LENGTH = 300;

export type ConsolidationCandidate = {
  id: string;
  categoryId: string;
  targetType: string | null;
  field: string;
  operator: string;
  pattern: string;
  enabled: number;
  isSystem: number;
  source: string;
  priority?: number;
  description?: string | null;
  excludedFromCalculation?: number;
};

export type ConsolidationGroup = {
  keepId: string;
  removeIds: string[];
  pattern: string;
  description: string | null;
};

function escapeRegexLiteral(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Parse only the escaped-literal alternation generated by the keyword editor. */
export function parseLiteralAlternation(pattern: string) {
  if (!pattern.startsWith("(?:") || !pattern.endsWith(")")) return null;
  const terms: string[] = [];
  let term = "";
  const body = pattern.slice(3, -1);
  for (let index = 0; index < body.length; index++) {
    const character = body[index]!;
    if (character === "\\") {
      const escaped = body[++index];
      if (!escaped || !/[.*+?^${}()|[\]\\]/u.test(escaped)) return null;
      term += escaped;
    } else if (character === "|") {
      if (!term) return null;
      terms.push(term);
      term = "";
    } else if (/[.*+?^${}()|[\]\\]/u.test(character)) {
      return null;
    } else {
      term += character;
    }
  }
  if (!term) return null;
  terms.push(term);
  return terms;
}

function ruleTerms(rule: ConsolidationCandidate) {
  if (rule.operator === "contains" && rule.pattern.length > 0)
    return [rule.pattern];
  if (rule.operator === "regex") return parseLiteralAlternation(rule.pattern);
  return null;
}

function eligible(rule: ConsolidationCandidate) {
  return rule.isSystem === 0 && rule.source === "user" && ruleTerms(rule);
}

function combinedDescription(members: readonly ConsolidationCandidate[]) {
  const descriptions = [
    ...new Set(
      members
        .map((rule) => rule.description?.trim())
        .filter((description): description is string => Boolean(description)),
    ),
  ];
  const description = descriptions.join("；");
  // Keep the canonical rule's original note if aggregating every note would
  // exceed the column/API limit. The matching terms themselves are never lost.
  return description.length <= 500
    ? description || null
    : descriptions[0] || null;
}

type PlannedGroup = ConsolidationGroup & {
  destination: ConsolidationCandidate;
  members: ConsolidationCandidate[];
  terms: string[];
  firstIndex: number;
};

/**
 * Aggregate compatible literal conditions by category, not by adjacency.
 * The retained row is the highest-priority row for that destination, so the
 * category keeps its existing place in the first-match order. Other
 * categories, disabled rules, system rules, and arbitrary user regexes remain
 * independent rules.
 */
export function planClassificationRuleConsolidation(
  rules: readonly ConsolidationCandidate[],
  maxPatternLength = MAX_KEYWORD_PATTERN_LENGTH,
) {
  const byDestination = new Map<string, PlannedGroup[]>();
  for (const [index, rule] of rules.entries()) {
    const terms = ruleTerms(rule);
    if (!eligible(rule) || !terms) continue;

    const destinationKey = JSON.stringify([
      rule.categoryId,
      rule.targetType,
      rule.field,
      rule.enabled,
      rule.excludedFromCalculation ?? 0,
    ]);
    const chunks = byDestination.get(destinationKey) ?? [];
    let group = chunks.at(-1);

    const proposedTerms = group ? [...group.terms] : [];
    const seen = new Set(
      proposedTerms.map((term) => term.toLocaleLowerCase("zh-TW")),
    );
    for (const term of terms) {
      const key = term.toLocaleLowerCase("zh-TW");
      if (!seen.has(key)) {
        proposedTerms.push(term);
        seen.add(key);
      }
    }
    const proposedPattern = `(?:${proposedTerms.map(escapeRegexLiteral).join("|")})`;

    if (!group || proposedPattern.length > maxPatternLength) {
      const singlePattern = `(?:${terms.map(escapeRegexLiteral).join("|")})`;
      if (singlePattern.length > maxPatternLength) continue;
      group = {
        keepId: rule.id,
        removeIds: [],
        pattern: singlePattern,
        description: rule.description?.trim() || null,
        destination: rule,
        members: [rule],
        terms: [...new Set(terms)],
        firstIndex: index,
      };
      chunks.push(group);
      byDestination.set(destinationKey, chunks);
      continue;
    }

    group.members.push(rule);
    group.removeIds.push(rule.id);
    group.terms = proposedTerms;
    group.pattern = proposedPattern;
    group.description = combinedDescription(group.members);
  }

  return [...byDestination.values()]
    .flat()
    .filter((group) => group.removeIds.length > 0)
    .sort((a, b) => a.firstIndex - b.firstIndex)
    .map(({ keepId, removeIds, pattern, description }) => ({
      keepId,
      removeIds,
      pattern,
      description,
    }));
}
